/// Config generation: emit ready-to-use training configs for HF Trainer, Axolotl, LLaMA-Factory.
use crate::design::architecture::ArchitectureSpec;
use crate::design::interview::{DesignInputs, TrainingApproach};

/// Emit a HuggingFace TrainingArguments-compatible YAML config.
pub fn generate_hf_trainer_config(inputs: &DesignInputs, spec: &ArchitectureSpec) -> String {
    let mut lines = vec![
        "# HuggingFace Trainer config".to_string(),
        "# Generated by TransXLab".to_string(),
        format!(
            "# Task: {}",
            if inputs.task_description.is_empty() {
                inputs.task_type.as_str()
            } else {
                &inputs.task_description
            }
        ),
        String::new(),
    ];

    // Model
    if inputs.approach == TrainingApproach::FineTune && !spec.base_model.is_empty() {
        lines.push(format!("model_name_or_path: \"{}\"", spec.base_model));
    }

    lines.push(String::new());
    lines.push("# Training arguments".to_string());

    if let Some(ref sched) = spec.schedule {
        lines.push("output_dir: \"./output\"".to_string());
        lines.push(format!("num_train_epochs: {}", sched.epochs));
        lines.push(format!("per_device_train_batch_size: {}", sched.batch_size));
        lines.push(format!(
            "per_device_eval_batch_size: {}",
            sched.batch_size
        ));
        lines.push(format!(
            "gradient_accumulation_steps: {}",
            sched.grad_accum_steps
        ));
        lines.push(format!("learning_rate: {:.1e}", sched.lr));
        lines.push(format!("weight_decay: {}", sched.weight_decay));
        lines.push(format!("warmup_steps: {}", sched.warmup_steps));
        lines.push("lr_scheduler_type: \"cosine\"".to_string());

        let use_bf16 = sched.precision == "bf16";
        lines.push(format!("bf16: {}", use_bf16));
        lines.push(format!("fp16: {}", !use_bf16));

        if sched.label_smoothing > 0.0 {
            lines.push(format!("label_smoothing_factor: {}", sched.label_smoothing));
        }

        lines.push("max_grad_norm: 1.0".to_string());
        lines.push("logging_steps: 10".to_string());
        lines.push("eval_strategy: \"steps\"".to_string());
        lines.push("eval_steps: 500".to_string());
        lines.push("save_strategy: \"steps\"".to_string());
        lines.push("save_steps: 500".to_string());
        lines.push("save_total_limit: 3".to_string());
        lines.push("load_best_model_at_end: true".to_string());
        lines.push("report_to: \"none\"".to_string());
    }

    if sched_is_lora(spec) {
        lines.push(String::new());
        lines.push("# Note: LoRA/QLoRA requires PEFT wrapper — see peft_config below".to_string());
    }

    lines.join("\n")
}

/// Emit a PEFT LoRA config (used alongside HF Trainer).
pub fn generate_peft_config(spec: &ArchitectureSpec) -> Option<String> {
    let lora = spec.lora_config.as_ref()?;
    let mut lines = Vec::new();
    lines.push("# PEFT LoRA config".to_string());
    lines.push("# Generated by TransXLab".to_string());
    lines.push(String::new());
    lines.push(format!("r: {}", lora.r));
    lines.push(format!("lora_alpha: {}", lora.alpha));
    lines.push(format!("lora_dropout: {}", lora.dropout));
    lines.push(format!(
        "target_modules:\n{}",
        lora.target_modules
            .iter()
            .map(|m| format!("  - \"{}\"", m))
            .collect::<Vec<_>>()
            .join("\n")
    ));
    lines.push("bias: \"none\"".to_string());
    lines.push("task_type: \"CAUSAL_LM\"".to_string());

    if spec.training_method == "qlora" {
        lines.push(String::new());
        lines.push("# QLoRA quantization".to_string());
        lines.push("quantization:".to_string());
        lines.push("  load_in_4bit: true".to_string());
        lines.push("  bnb_4bit_compute_dtype: \"bfloat16\"".to_string());
        lines.push("  bnb_4bit_quant_type: \"nf4\"".to_string());
        lines.push("  bnb_4bit_use_double_quant: true".to_string());
    }

    Some(lines.join("\n"))
}

/// Emit an Axolotl-compatible YAML config.
pub fn generate_axolotl_config(inputs: &DesignInputs, spec: &ArchitectureSpec) -> String {
    let mut lines = Vec::new();
    lines.push("# Axolotl config".to_string());
    lines.push("# Generated by TransXLab".to_string());
    lines.push(String::new());

    if inputs.approach == TrainingApproach::FineTune && !spec.base_model.is_empty() {
        lines.push(format!("base_model: \"{}\"", spec.base_model));
        lines.push("model_type: \"AutoModelForCausalLM\"".to_string());
    }

    lines.push("tokenizer_type: \"AutoTokenizer\"".to_string());
    lines.push(String::new());

    // LoRA
    if let Some(ref lora) = spec.lora_config {
        lines.push("adapter: \"lora\"".to_string());
        lines.push(format!("lora_r: {}", lora.r));
        lines.push(format!("lora_alpha: {}", lora.alpha));
        lines.push(format!("lora_dropout: {}", lora.dropout));
        lines.push(format!(
            "lora_target_modules:\n{}",
            lora.target_modules
                .iter()
                .map(|m| format!("  - \"{}\"", m))
                .collect::<Vec<_>>()
                .join("\n")
        ));
        if spec.training_method == "qlora" {
            lines.push("load_in_4bit: true".to_string());
        }
        lines.push(String::new());
    }

    // Data
    lines.push("datasets:".to_string());
    lines.push("  - path: \"./data/train.jsonl\"".to_string());
    lines.push("    type: \"completion\"".to_string());
    lines.push(String::new());

    lines.push("val_set_size: 0.1".to_string());
    lines.push("output_dir: \"./output\"".to_string());
    lines.push(String::new());

    // Training
    if let Some(ref sched) = spec.schedule {
        lines.push(format!("num_epochs: {}", sched.epochs));
        lines.push(format!(
            "micro_batch_size: {}",
            sched.batch_size
        ));
        lines.push(format!(
            "gradient_accumulation_steps: {}",
            sched.grad_accum_steps
        ));
        lines.push(format!("learning_rate: {:.1e}", sched.lr));
        lines.push(format!("weight_decay: {}", sched.weight_decay));
        lines.push(format!("warmup_steps: {}", sched.warmup_steps));
        lines.push("lr_scheduler: \"cosine\"".to_string());
        lines.push("bf16: true".to_string());
        lines.push("max_grad_norm: 1.0".to_string());
        lines.push(String::new());
        lines.push("logging_steps: 10".to_string());
        lines.push("eval_steps: 500".to_string());
        lines.push("save_steps: 500".to_string());
        lines.push("save_total_limit: 3".to_string());
    }

    lines.join("\n")
}

/// Emit a LLaMA-Factory compatible YAML config.
pub fn generate_llamafactory_config(inputs: &DesignInputs, spec: &ArchitectureSpec) -> String {
    let mut lines = vec![
        "# LLaMA-Factory config".to_string(),
        "# Generated by TransXLab".to_string(),
        String::new(),
    ];

    lines.push("### model".to_string());
    if inputs.approach == TrainingApproach::FineTune && !spec.base_model.is_empty() {
        lines.push(format!("model_name_or_path: \"{}\"", spec.base_model));
    }
    lines.push(String::new());

    lines.push("### method".to_string());
    lines.push("stage: \"sft\"".to_string());
    lines.push("do_train: true".to_string());

    if let Some(ref lora) = spec.lora_config {
        lines.push("finetuning_type: \"lora\"".to_string());
        lines.push(format!("lora_rank: {}", lora.r));
        lines.push(format!("lora_alpha: {}", lora.alpha));
        lines.push(format!("lora_dropout: {}", lora.dropout));
        lines.push(format!(
            "lora_target: \"{}\"",
            lora.target_modules.join(",")
        ));
        if spec.training_method == "qlora" {
            lines.push("quantization_bit: 4".to_string());
        }
    } else {
        lines.push("finetuning_type: \"full\"".to_string());
    }
    lines.push(String::new());

    lines.push("### dataset".to_string());
    lines.push("dataset: \"custom_train\"".to_string());
    lines.push("template: \"default\"".to_string());
    lines.push(String::new());

    lines.push("### output".to_string());
    lines.push("output_dir: \"./output\"".to_string());
    lines.push(String::new());

    lines.push("### train".to_string());
    if let Some(ref sched) = spec.schedule {
        lines.push(format!("num_train_epochs: {:.1}", sched.epochs as f64));
        lines.push(format!(
            "per_device_train_batch_size: {}",
            sched.batch_size
        ));
        lines.push(format!(
            "gradient_accumulation_steps: {}",
            sched.grad_accum_steps
        ));
        lines.push(format!("learning_rate: {:.1e}", sched.lr));
        lines.push(format!("weight_decay: {}", sched.weight_decay));
        lines.push(format!("warmup_steps: {}", sched.warmup_steps));
        lines.push("lr_scheduler_type: \"cosine\"".to_string());
        lines.push("bf16: true".to_string());
        lines.push("max_grad_norm: 1.0".to_string());
        lines.push(String::new());
        lines.push("logging_steps: 10".to_string());
        lines.push("save_steps: 500".to_string());
        lines.push("save_total_limit: 3".to_string());
    }

    lines.join("\n")
}

fn sched_is_lora(spec: &ArchitectureSpec) -> bool {
    spec.training_method == "lora" || spec.training_method == "qlora"
}

/// Save all config variants to the output directory.
pub fn save_configs(
    output_dir: &std::path::Path,
    inputs: &DesignInputs,
    spec: &ArchitectureSpec,
) -> std::io::Result<()> {
    let configs_dir = output_dir.join("configs");
    std::fs::create_dir_all(&configs_dir)?;

    std::fs::write(
        configs_dir.join("hf_trainer.yaml"),
        generate_hf_trainer_config(inputs, spec),
    )?;

    if let Some(peft) = generate_peft_config(spec) {
        std::fs::write(configs_dir.join("peft_lora.yaml"), peft)?;
    }

    std::fs::write(
        configs_dir.join("axolotl.yaml"),
        generate_axolotl_config(inputs, spec),
    )?;

    std::fs::write(
        configs_dir.join("llamafactory.yaml"),
        generate_llamafactory_config(inputs, spec),
    )?;

    Ok(())
}
